name: 'Amazon ECS "Deploy Task Definition" Action for GitHub Actions'
description: 'Registers an Amazon ECS task definition, does not deploy'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition file to register'
    required: true
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'

runs:
  using: 'node20'
  main: 'dist/index.js'
